change the port configuration for fwd and some struct modify.
rbaryanai/vnet pull request #3
Opened 2021-03-10 06:13 UTC by BillZhou734

Signed-off-by: Dong Zhou <dongzhou@nvidia.com>

2021-03-10 13:45 UTC, rbaryanai requested changes

2021-03-10 13:45 UTC, rbaryanai commented on examples/vnet/doca_gw.c
> +struct doca_gw_port * doca_gw_port_start(struct doca_gw_port *port, struct doca_gw_error *err)
This is user API, if user need to provide the port struct then it means you expose implementation. it blocks from having any implementation in the future. please remain with CFG and PORT

2021-03-10 13:45 UTC, rbaryanai commented on examples/vnet/doca_gw.c
> +			ret = doca_gw_dpdk_start_port(port->port_id, cfg, (struct doca_dpdk_port*)port->user_data);
cfg->port

2021-03-10 13:45 UTC, rbaryanai commented on examples/vnet/doca_gw.c
> +struct doca_gw_port * doca_gw_port_start(struct doca_gw_port *port, struct doca_gw_error *err)
use this API:
struct doca_gw_port * doca_gw_port_start(struct doca_gw_port_cfg *cfg, struct doca_gw_error *err)

2021-03-10 13:45 UTC, rbaryanai commented on examples/vnet/doca_gw.h
> +            uint16_t queues[MAX_RSS_QUEUE]; // reduce malloc ?
why? this is a cfg object it should be done once in most cases.
putting a restriction here is not good. 16 might be too small

2021-03-10 13:45 UTC, rbaryanai commented on examples/vnet/doca_gw.h
> +        struct port {
can you use line space here between different logical sturcutres, it is more readable

2021-03-10 13:45 UTC, rbaryanai commented on examples/vnet/gw.c
> +		.rss = { .rss_flags = DOCA_RSS_IP, .queues = {0,3,4},.num_queues = 3,},
i don't understand why RSS is a port parameter. I can have two different RSS actions for same port right? one using port 01 and second 2 3, or 0123 ...etc. so this should not be part of the port. RSS if FWD configuration.

2021-03-10 13:45 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.h
> +extern void doca_dump_gw_match(struct doca_gw_match *match);
we need to make make it some compile option to help us debug. it is ok now, but generally no externs in code please.

2021-03-10 13:45 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
>  			doca_gw_dpdk_build_rss_action(action_entry, fwd_cfg);
I think you should test the cfg and if it is valid, save it for later and give user a handle. when user adds it in the pipeline you call it. you can put function pointer for implementation.

2021-03-11 02:45 UTC, BillZhou734 commented on examples/vnet/gw.c
> +		.rss = { .rss_flags = DOCA_RSS_IP, .queues = {0,3,4},.num_queues = 3,},
there i define fwd:"def_fwd" and "offload_fwd".
"def_fwd":  for default match packetes, will create flow. maybe some special core to handle it . 
"offload_fwd": for packets after offload.
I think this two part will be separated...

2021-03-11 02:58 UTC, BillZhou734 commented on examples/vnet/doca_gw_dpdk.c
>  			doca_gw_dpdk_build_rss_action(action_entry, fwd_cfg);
gw layer -> dpdk layer, i think we can check it once in gw layer,  right ?

2021-03-11 03:12 UTC, BillZhou734 commented on examples/vnet/doca_gw_dpdk.h
> +extern void doca_dump_gw_match(struct doca_gw_match *match);
todo next patch.

2021-03-11 03:17 UTC, BillZhou734 commented on examples/vnet/doca_gw.h
> +        struct port {
done

2021-03-18 07:33 UTC, BillZhou734 commented on examples/vnet/doca_gw.c
> +struct doca_gw_port * doca_gw_port_start(struct doca_gw_port *port, struct doca_gw_error *err)
done

2021-03-18 09:50 UTC, BillZhou734 commented
close it , since too many different for the new PR

2021-03-18 09:50 UTC, closed without merging

2021-03-18 11:33 UTC, rbaryanai requested changes

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw.c
> +		err->message = "alloc gw port null.";
maybe OOM

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw.c
> +			ret = doca_gw_dpdk_start_port(port->port_id, &port->cfg, (struct doca_dpdk_port*)port->user_data);
port_id? you don't have it here

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw.c
> +//can move those define to doca_gw.h ?
no. on more complex scenario you will need a real object here,.

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw.c
> +			ret = doca_gw_dpdk_start_port(port->port_id, cfg, (struct doca_dpdk_port*)port->user_data);
? where do you set port_id?

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw.h
> +    uint16_t queues;				//only can do nb_queue rss, can use doca_fwd_table_cfg  ?
yes, you are right.

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw.h
> +		uint64_t ebs;//need ?
we can take out because we don't implement it now anyway.

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
> +		*spec = rte_cpu_to_be_32(match->tun.gre.key);
user should put everything in network order. we keep all our data in network order. This is the rule.

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
> +	*spec = rte_cpu_to_be_32(match->tun.gre.key);
should be set by user in network order, we don't need to siwtch,

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
> +	*mask = 0xffff;
key is uint32_t so mask is not good

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
> +{
if we have a match on key, we need to make sure key flag is 1 on GRE header

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
>  			doca_gw_dpdk_build_vxlan_flow_item(NEXT_ITEM, match);
there is an assumption here that GRE is always with a key, we need to make sure that when user build the pipeline he configures the vni.

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
> +	return meter_prof_id++;
meter_prof_is a naive approach, user can add and delete and you don't have a way to track what is in use and what not.

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
> +	return meter_id++;
need a pool

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
> +	/*create meter*/
we will need to use new API when it is ready right?

2021-03-18 11:33 UTC, rbaryanai commented on examples/vnet/doca_gw_dpdk.c
> +{
it is a good start, build please note that user can set different CBS/CIR for each flow on same pipe. so you will need to handle profiles and meters id inside the pipeline_entry struct,